name: Setup Kind
description: Sets up a kind cluster and installs Helm and kubectl
outputs:
  helm-path:
    description: The path to the Helm binary
    value: ${{ steps.helm.outputs.helm-path }}
  kubectl-path:
    description: The path to the kubectl binary
    value: ${{ steps.kubectl.outputs.kubectl-path }}
runs:
  using: composite
  steps:
    - id: helm
      name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.16.2

    - id: kubectl
      name: Install kubectl
      uses: azure/setup-kubectl@v4

    - name: Create kind cluster
      uses: helm/kind-action@v1.10.0
