name: continuous-delivery

on:
  pull_request:

jobs:
  install_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.3

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0

      - name: Deploy using helm chart
        run: |
          helm upgrade --install edb-pg4k --namespace postgresql-operator-system \
          --create-namespace charts/edb-postgres-for-kubernetes --wait

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2

      - name: Deploy a cluster
        run: |
          cat <<EOF | kubectl apply -f -
          # Example of PostgreSQL cluster
          apiVersion: postgresql.k8s.enterprisedb.io/v1
          kind: Cluster
          metadata:
            name: cluster-example
          spec:
            instances: 3
            storage:
             size: 1Gi
          EOF

          ITER=0
          while true; do
            if [[ $ITER -ge 300 ]]; then
              echo "Cluster not ready"
              exit 1
            fi
            READY_INSTANCES=$(kubectl get cluster cluster-example -o jsonpath='{.status.readyInstances}')
            if [[ "$READY_INSTANCES" == 3 ]]; then
              echo "Cluster up and running"
              break
            fi
            sleep 1
            (( ++ITER ))
          done
