name: continuous-delivery

on:
  pull_request:
  workflow_dispatch:

jobs:

  change-triage:
    name: Check changed files
    runs-on: ubuntu-22.04
    outputs:
      pg4k-pgd-changed: ${{ steps.filter.outputs.pg4k-pgd-changed }}
      ep4k-changed: ${{ steps.filter.outputs.ep4k-changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Check for changes
        uses: dorny/paths-filter@v2.11.1
        id: filter
        with:
          base: ${{ (github.event_name == 'schedule') && 'main' || '' }}
          filters: |
            pg4k-pgd-changed:
              - 'charts/edb-postgres-distributed-for-kubernetes/**'
            ep4k-changed:
              - 'charts/edb-postgres-for-kubernetes/**'

  deploy-ep4k:
    runs-on: ubuntu-22.04
    needs:
      - change-triage
    if: needs.change-triage.outputs.ep4k-changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.3

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0

      - name: Deploy using helm chart
        run: |
          helm upgrade --install edb-pg4k --namespace postgresql-operator-system \
          --create-namespace charts/edb-postgres-for-kubernetes --wait

      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2

      - name: Deploy a cluster
        run: |
          kubectl apply -f hack/samples/ep4k-cluster.yaml

          PHASE="Cluster in healthy state"
          kubectl wait --timeout=5m --for=jsonpath='{.status.phase}'="$PHASE" clusters/cluster-example

  deploy-pg4k-pgd:
    runs-on: ubuntu-22.04
    needs:
      - change-triage
    if: needs.change-triage.outputs.pg4k-pgd-changed == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.3

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0

      - name: Deploy using helm chart
        run: |
          helm dependency build charts/edb-postgres-distributed-for-kubernetes
          helm upgrade --install edb-pg4k-pgd --namespace pgd-operator-system \
          --create-namespace charts/edb-postgres-distributed-for-kubernetes  \
          --set image.imageCredentials.username=${{ secrets.CS_USER }} \
          --set image.imageCredentials.password=${{ secrets.CS_PASSWORD }} \
          --wait --timeout 10m


      - name: Install kubectl
        uses: azure/setup-kubectl@v3.2

      - name: Deploy a cluster
        run: |
          kubectl apply -f hack/samples/issuer-selfsigned.yaml
          kubectl apply -f hack/samples/pg4k-pgd-cluster.yaml

          PHASE="PGDGroup - Healthy"
          kubectl wait --timeout=5m --for=jsonpath='{.status.phase}'="$PHASE" pgdgroups/region-a
          kubectl wait --timeout=5m --for=jsonpath='{.status.phase}'="$PHASE" pgdgroups/region-b
          kubectl wait --timeout=5m --for=jsonpath='{.status.phase}'="$PHASE" pgdgroups/region-c
