# Create a tag when a PR on a release branch is merged

name: release-tag

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v7
      -
        name: Temporarily disable "include administrators" branch protection
        if: always() && github.ref == 'refs/heads/main'
        id: disable_include_admins
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ secrets.REPO_GHA_PAT }}
          script: |
            const params = {
              owner: 'EnterpriseDB',
              repo: 'edb-postgres-for-kubernetes-charts',
              branch: 'main',
            };
            const { data } = await github.rest.repos.getAdminBranchProtection(params);
            core.setOutput('initial_status', data.enabled);
            if (data.enabled) {
              await github.rest.repos.deleteAdminBranchProtection(params);
            }
      -
        name: Create tag
        id: create_tag
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
        uses: christophebedard/tag-version-commit@v1.7.0
        with:
          token: ${{ secrets.REPO_GHA_PAT }}
          version_regex: '^Release ([a-z0-9-]+-v[0-9]+\.[0-9]+\.[0-9]+)'
          dry_run: false
      - name: Fail if tag was not created
        if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && steps.create_tag.outputs.tag == ''
        run: |
          echo "::error::Commit title did not match version regex — no tag was created."
          exit 1
      -
        name: Enable "include administrators" branch protection
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        if: |
          always() &&
          github.ref == 'refs/heads/main' &&
          steps.disable_include_admins.outputs.initial_status == 'true'
        with:
          github-token: ${{ secrets.REPO_GHA_PAT }}
          script: |
            await github.rest.repos.setAdminBranchProtection({
              owner: 'EnterpriseDB',
              repo: 'edb-postgres-for-kubernetes-charts',
              branch: 'main',
            });
